# Configuration time: Mon May 16 03:41:24 EDT 1994
# Configured by: rsanders
# Target system: linux hrothgar 1.1.12 #9 sat may 14 02:03:23 edt 1994 i486 
osname='linux'
osvers='1.0'
bin='/usr/bin' 
ccflags='-I/usr/include/bsd'
cppflags=' -I/usr/include/bsd'
d_dosuid='define'
d_voidsig='define'
gidtype='gid_t'
groupstype='gid_t'
installprivlib='/usr/lib/perl5'
malloctype='void *'
nm_opt=''
optimize='-O2'
runnm='false'
so='o'
sig_name='ZERO HUP INT QUIT ILL TRAP IOT UNUSED FPE KILL USR1 SEGV USR2 PIPE ALRM TERM STKFLT CHLD CONT STOP TSTP TTIN TTOU IO XCPU XFSZ VTALRM PROF WINCH'
signal_t='void'
uidtype='uid_t'
usemymalloc='n'
usenm='false'
yacc='bison -y'
