#!./perl

# $RCSfile: dbm.t,v $$Revision: 4.1 $$Date: 92/08/07 18:27:43 $

BEGIN {
    @INC = '../lib';
}

require NDBM_File;
use POSIX 'fcntl_h';

unlink <Op.dbmx*>;

tie(%h,NDBM_File,'Op.dbmx', O_RDWR|O_CREAT, 0640);

$h{'goner2'} = 'snork';
delete $h{'goner2'};

print $h{'goner2'};
